# Generated by Django 4.1.5 on 2023-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='cantidad_a_comprar',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='aclaracion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='capsulas',
            old_name='cantidad_a_comprar',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='capsulas',
            old_name='fecha_de_entrega',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='capsulas',
            old_name='aclaracion',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='te',
            old_name='cantidad_a_comprar',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='te',
            old_name='fecha_de_entrega',
            new_name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='cafe',
            name='precio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='capsulas',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='precio',
            field=models.TextField(null=True),
        ),
    ]
