# Generated by Django 4.1.5 on 2023-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_rename_cantidad_a_comprar_cafe_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
